name: ci-dockerhub 
on: 
 push: 
 branches: [ "main" ] 
 tags: [ "*" ] 
 pull_request: 
 branches: [ "main" ] 
jobs: 
 build-test-push: 
 runs-on: ubuntu-latest 
 steps: 
 - name: Checkout 
 uses: actions/checkout@v4 
 - name: Set up Python 
 uses: actions/setup-python@v5 
 with: 
 python-version: '3.11' 
 - name: Install deps 
 run: | 
 python -m pip install --upgrade pip 
 pip install -r requirements.txt 
 - name: Run tests 
 run: pytest -q 
 - name: Docker meta 
 id: meta 
 uses: docker/metadata-action@v5 
 with: 
 images: ${{ secrets.DOCKERHUB_USERNAME }}/python-ci-lab
 tags: | 
 type=raw,value=latest,enable={{is_default_branch}} 
 type=sha,prefix=sha-,format=short 
 type=ref,event=tag 
 - name: Set up QEMU 
 uses: docker/setup-qemu-action@v3 
 - name: Set up Docker Buildx 
 uses: docker/setup-buildx-action@v3 
 - name: Login to Docker Hub 
 uses: docker/login-action@v3 
 with: 
 username: ${{ secrets.DOCKERHUB_USERNAME }} 
 password: ${{ secrets.DOCKERHUB_TOKEN }} 
 - name: Build and push 
 uses: docker/build-push-action@v6 
 with: 
 context: . 
 push: true 
 tags: ${{ steps.meta.outputs.tags }} 
 labels: ${{ steps.meta.outputs.labels }} 
 platforms: linux/amd64 
